STOP_WORDS = {
	"a", "about", "above", "after", "again", "against", "all", "am", "an", "and",
	"any", "are", "aren't", "as", "at", "be", "because", "been", "before", "being",
	"below", "between", "both", "but", "by", "can't", "cannot", "could", "couldn't",
	"did", "didn't", "does", "doesn't", "doing", "don't", "down", "during", "each",
	"few", "for", "from", "further", "had", "hadn't", "has", "hasn't", "have", "haven't",
	"having", "he", "he'd", "he'll", "he's", "her", "here", "here's", "hers", "herself",
	"him", "himself", "his", "how", "how's", "i", "i'd", "i'll", "i'm", "i've", "if",
	"in", "into", "is", "isn't", "it", "it's", "its", "itself", "just", "ll", "ma", "me",
	"mightn't", "more", "most", "mustn't", "my", "myself", "needn't", "no", "nor", "not",
	"now", "of", "off", "on", "once", "only", "or", "other", "our", "ours", "ourselves", "out",
	"over", "own", "re", "s", "same", "shan't", "she", "she'd", "she'll", "she's", "should",
	"shouldn't", "so", "some", "such", "t", "than", "that", "that's", "the", "their", "theirs",
	"them", "themselves", "then", "there", "there's", "these", "they", "they'd", "they'll", "they're", "they've",
	"this", "those", "through", "to", "too", "under", "until", "up", "ve", "very", "was", "wasn't",
}